/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import com.mysql.jdbc.StringUtils;
import connexion.Connexion;
import entities.Departement;
import daos.DepartementDAO;
import java.sql.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrateur
 */
public class JIFDepartementCrud extends javax.swing.JInternalFrame {

    Connection connexion = Connexion.seConnecter("localhost", "3306", "root", "", "cinescope2014");

    /**
     * Creates new form NJFDeparteementCrud
     */
    public JIFDepartementCrud() throws SQLException, ClassNotFoundException {
        initComponents();
        setVisible(true);

        // Class.forName("org.gjt.mm.mysql.Driver");
        DepartementDAO DAO = new DepartementDAO(connexion);
        DefaultTableModel ldtm = (DefaultTableModel) jTableDepartement.getModel();

        try {
            System.out.println("***** LISTE DEPARTEMENT *****");
            List<Departement> liste = DAO.selectAll();
            Object[] tLigne;

            for (int i = 0; i < liste.size(); i++) {
                Departement d = liste.get(i);

                tLigne = new Object[3];
                tLigne[0] = d.getIdDepartement();
                tLigne[1] = d.getCodeDepartement();
                tLigne[2] = d.getNomDepartement();

                ldtm.addRow(tLigne);
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartement = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonInsert = new javax.swing.JButton();
        FieldIdDepartement = new javax.swing.JTextField();
        FieldCodeDepartement = new javax.swing.JTextField();
        FieldNomDepartement = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        ButtonDelete = new javax.swing.JButton();
        ButtonSelect = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("liste Departement");

        jTableDepartement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Nom"
            }
        ));
        jTableDepartement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDepartement);

        jLabel1.setText("Id");

        ButtonInsert.setText("Insert");
        ButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertActionPerformed(evt);
            }
        });

        FieldIdDepartement.setText("Id departement");
        FieldIdDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIdDepartementActionPerformed(evt);
            }
        });

        FieldCodeDepartement.setText("Code departement");
        FieldCodeDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCodeDepartementActionPerformed(evt);
            }
        });

        FieldNomDepartement.setText("Nom departement");

        jLabel2.setText("Code");

        Nom.setText("Nom");

        ButtonDelete.setText("Delete");

        ButtonSelect.setText("Select");
        ButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelectActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("Update");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        jLabelMessage.setText("MESSAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(Nom))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldCodeDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldIdDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FieldNomDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ButtonSelect)
                                            .addComponent(ButtonUpdate))
                                        .addGap(165, 165, 165))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(ButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldIdDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ButtonUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ButtonInsert)
                        .addComponent(ButtonDelete))
                    .addComponent(FieldCodeDepartement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nom)
                    .addComponent(FieldNomDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldIdDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIdDepartementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIdDepartementActionPerformed

    private void ButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertActionPerformed
        // TODO add your handling code here:
        Connection connexion = Connexion.seConnecter("localhost", "3306", "root", "", "cinescope2014");
        DepartementDAO DAO = new DepartementDAO(connexion);
        Departement insert = new Departement(FieldCodeDepartement.getText(), FieldNomDepartement.getText());
        DAO.insert(insert);

    }//GEN-LAST:event_ButtonInsertActionPerformed

    private void ButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSelectActionPerformed
        // TODO add your handling code here:
        Connection connexion = Connexion.seConnecter("localhost", "3306", "root", "", "cinescope2014");

        DefaultTableModel ldtm = (DefaultTableModel) jTableDepartement.getModel();
       
        for (int row = ldtm.getRowCount() - 1; row >= 0; row--) {

            System.out.println(ldtm.getRowCount() + " row= " + row);
            ldtm.removeRow(row);
        }

        DepartementDAO DAO = new DepartementDAO(connexion);
        try {
            List<Departement> liste = DAO.selectAll();
            Object[] tLigne;

            for (int i = 0; i < liste.size(); i++) {
                Departement d = liste.get(i);
                tLigne = new Object[3];
                tLigne[0] = d.getIdDepartement();
                tLigne[1] = d.getCodeDepartement();
                tLigne[2] = d.getNomDepartement();
                ldtm.addRow(tLigne);
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_ButtonSelectActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!FieldCodeDepartement.getText().isEmpty()|| !FieldCodeDepartement.getText().equals(" ")) {
            Connection connexion2 = Connexion.seConnecter("localhost", "3306", "root", "", "cinescope2014");
            Departement upDate = new Departement(Integer.parseInt(FieldIdDepartement.getText()), FieldCodeDepartement.getText(), FieldNomDepartement.getText());
            DepartementDAO dao = new DepartementDAO(connexion2);
            dao.update(upDate);
            
            FieldIdDepartement.setText("1");
            FieldNomDepartement.setText(" ");
            FieldCodeDepartement.setText(" ");
            
        } else {

            jLabelMessage.setText("Veillez");
            System.out.println("saisir parametres");
        }

    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void FieldCodeDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCodeDepartementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCodeDepartementActionPerformed

   
    private void jTableDepartementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartementMouseClicked
        // TODO add your handling code here:
        /*  int liRow = jTable1.getSelectedRow();
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
        //tJTexts[i].setText(jTableTable.getValueAt(liRow, i).toString());
        idtmEnr.setValueAt(jTable1.getValueAt(liRow, i), i, 1);
        }*/
    }//GEN-LAST:event_jTableDepartementMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonInsert;
    private javax.swing.JButton ButtonSelect;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTextField FieldCodeDepartement;
    private javax.swing.JTextField FieldIdDepartement;
    private javax.swing.JTextField FieldNomDepartement;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartement;
    // End of variables declaration//GEN-END:variables

}
