/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;


import java.sql.*;
//import connexion.Connexion;

/**
 *
 * @author formation
 */
public class JIFPaysAjout extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIPaysAjout
     */
    Connection connexion_bd;
    Statement execut_SQL;
    ResultSet resultat_BD;

    // --- Pour une connexion execut_SQL native
    String localhost = "127.0.0.1";
    String Port = "3306";
    String nom_BD = "cinescope2014";
    String user = "root";
    String mdp = "";
    String pilote = "org.gjt.mm.mysql.Driver";
    String url = "jdbc:mysql://" + localhost + ":" + Port + "/" + nom_BD;
    String requete_SQL = "INSERT INTO pays(NOM_pays, MASCULIN, FEMININ, NEUTRE ) VALUES(?, ?, ?, ?)";

    public JIFPaysAjout() {
       initComponents();
       setVisible(true);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomPays = new javax.swing.JLabel();
        jLabelMasculin = new javax.swing.JLabel();
        jLabelFeminin = new javax.swing.JLabel();
        jLabelNeutre = new javax.swing.JLabel();
        jTextFieldNomPAys = new javax.swing.JTextField();
        jTextFieldPaysMasculin = new javax.swing.JTextField();
        jTextFieldPaysFemin = new javax.swing.JTextField();
        jTextFieldPaysNeutre = new javax.swing.JTextField();
        jButtonPaysAjouter = new javax.swing.JButton();
        jLabelPaysMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nouveau Pays");

        jLabelNomPays.setText("Nom Pays");

        jLabelMasculin.setText("Masculin");

        jLabelFeminin.setText("Feminin");

        jLabelNeutre.setText("Neutre");

        jTextFieldNomPAys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomPAysActionPerformed(evt);
            }
        });

        jTextFieldPaysMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaysMasculinActionPerformed(evt);
            }
        });

        jTextFieldPaysFemin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaysFeminActionPerformed(evt);
            }
        });

        jButtonPaysAjouter.setText("Ajouter");
        jButtonPaysAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaysAjouterActionPerformed(evt);
            }
        });

        jLabelPaysMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPaysAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelNomPays)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelMasculin)
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelFeminin)
                                            .addGap(31, 31, 31)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNeutre)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPaysNeutre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPaysFemin)
                                    .addComponent(jTextFieldPaysMasculin)
                                    .addComponent(jTextFieldNomPAys)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelPaysMessage)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomPays)
                    .addComponent(jTextFieldNomPAys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMasculin)
                    .addComponent(jTextFieldPaysMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFeminin)
                    .addComponent(jTextFieldPaysFemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNeutre)
                    .addComponent(jTextFieldPaysNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButtonPaysAjouter)
                .addGap(18, 18, 18)
                .addComponent(jLabelPaysMessage)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomPAysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomPAysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomPAysActionPerformed

    private void jTextFieldPaysMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaysMasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaysMasculinActionPerformed

    private void jButtonPaysAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaysAjouterActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName(pilote);
            //tentative de connexion a la BD//Connection connexion = Connexion.seConnecter("localhost", "3306",  "root", "", "cinescope2014");
            
            connexion_bd = DriverManager.getConnection(url, user, mdp);
            //Création d'un objet Statement pour execution requete SQL
           // execut_SQL = connexion_bd.createStatement();
            //On crée l'objet avec la requête en paramètre
            PreparedStatement requete_prepare = connexion_bd.prepareStatement(requete_SQL);
            //L'objet ResultSet contient le résultat de la requête SQL
            //resultat_BD = execut_SQL.executeQuery(requete_SQL);
            requete_prepare.setString(1, jTextFieldNomPAys.getText());
            requete_prepare.setString(2, jTextFieldPaysMasculin.getText());
            requete_prepare.setString(3, jTextFieldPaysFemin.getText());
            requete_prepare.setString(4, jTextFieldPaysNeutre.getText());
            requete_prepare.executeUpdate();

            // resultat_BD.close();
           // execut_SQL.close();
            connexion_bd.close();

        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonPaysAjouterActionPerformed

    private void jTextFieldPaysFeminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaysFeminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaysFeminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPaysAjouter;
    private javax.swing.JLabel jLabelFeminin;
    private javax.swing.JLabel jLabelMasculin;
    private javax.swing.JLabel jLabelNeutre;
    private javax.swing.JLabel jLabelNomPays;
    private javax.swing.JLabel jLabelPaysMessage;
    private javax.swing.JTextField jTextFieldNomPAys;
    private javax.swing.JTextField jTextFieldPaysFemin;
    private javax.swing.JTextField jTextFieldPaysMasculin;
    private javax.swing.JTextField jTextFieldPaysNeutre;
    // End of variables declaration//GEN-END:variables

   
}
