/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author formation
 */
public class JIFPaysVisu extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIPaysVisu
     */
    /**
     * Creates new form JIPaysAjout
     */
    Connection connexion_bd;
    Statement execut_SQL;
    ResultSet resultat_BD;

    // --- Pour une connexion execut_SQL native
    String localhost = "127.0.0.1";
    String Port = "3306";
    String nom_BD = "cinescope2014";
    String user = "root";
    String mdp = "";
    String pilote = "org.gjt.mm.mysql.Driver";
    String url = "jdbc:mysql://" + localhost + ":" + Port + "/" + nom_BD;
    String requete_SQL = "SELECT * FROM pays";

    public JIFPaysVisu() throws ClassNotFoundException {

        initComponents();
        setVisible(true);
        setTitle("liste Pays");

        /**
         * ***********
         */
        try {
            Class.forName(pilote);
            //tentative de connexion a la BD
            connexion_bd = DriverManager.getConnection(url, user, mdp);
            //Création d'un objet Statement pour execution requete SQL
            execut_SQL = connexion_bd.createStatement();
            //L'objet ResultSet contient le résultat de la requête SQL
            resultat_BD = execut_SQL.executeQuery(requete_SQL);
            //On récupère les MetaData
            ResultSetMetaData resultMeta = resultat_BD.getMetaData();
            
            DefaultTableModel ldtm = (DefaultTableModel) jTablePays.getModel();
            Object[] tLigne;

            while (resultat_BD.next()) {
                tLigne = new Object[resultMeta.getColumnCount()];
                int i=1;
                    for (int j = 0; j < resultMeta.getColumnCount(); j++) {
                        tLigne[j] = resultat_BD.getObject(i);
                        i++;
                    }
                
                ldtm.addRow(tLigne);
            }
             
          

            resultat_BD.close();
            execut_SQL.close();
            connexion_bd.close();

        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }

        /**
         * ************
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePays = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VisuPays");

        jTablePays.setAutoCreateRowSorter(true);
        jTablePays.setBackground(new java.awt.Color(204, 204, 204));
        jTablePays.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Masculin", "Feminin", "Neutre"
            }
        ));
        jScrollPane1.setViewportView(jTablePays);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePays;
    // End of variables declaration//GEN-END:variables
}
